language: python

python:
  - "3.4"

cache:
  pip:
  apt:
  directories:
    - .tox

env:
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py34-django17
  - TOX_ENV=py34-django18
  - TOX_ENV=py34-django19
  - TOX_ENV=py35-django17
  - TOX_ENV=py35-django18
  - TOX_ENV=py35-django19
  

after_failure:
  - cat /home/travis/.pip/pip.log

after_success:
  - coveralls

install:
  - pip install pip wheel
  - pip install -q coveralls tox

script:
  - env | sort
  - tox -e $TOX_ENV

